settings:
  delay: 10 # Задержка между использованием команды (в секундах)

messages:
  moderator_chat: "&bПомощь &7» &cИгрок &b[player] &cпросит спека"
  title: "&cВнимание в чат!"
  subtitle: "&eИгрок просит спека"
  player_message: "&bПомощь &7» &cВаш запрос на спек отправлен модератору, ожидайте помощи!"
  cooldown: "&bПомощь &7» &cВы должны подождать [time] секунд перед повторным использованием команды."
  no_permission: "&cУ вас нет разрешения на использование этой команды."
  reload_success: "&bПомощь &7» &aКонфигурация успешно перезагружена."
  no_reload_permission: "&cУ вас нет прав на перезагрузку конфигурации."
  no_moderator_permission: "&cМодераторы не могут использовать эту команду."